version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"

  axon-server:
    image: axoniq/axonserver:3.9
    container_name: axon-server
    restart: unless-stopped
    ports:
      - "8024:8024"   # Axon Server UI
      - "8124:8124"   # Axon Server gRPC
    environment:
      AXONSERVER_NAME: axon-server
